import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ContextProvider } from "@/context/provider";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased bg-primary/15 flex flex-col w-full min-h-screen items-center justify-center",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <div className="flex w-full max-w-5xl min-h-screen bg-background shadow-4xl shadow-border border-l-8 border-primary">
          <ContextProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </ContextProvider>
        </div>
      </body>
    </html>
  );
}
