import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ContextProvider } from "@/context/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased bg-primary-foreground flex flex-col w-full min-h-screen items-center justify-center",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <div className="flex w-full max-w-5xl min-h-screen p-2 items-center justify-center bg-background shadow-2xl shadow-primary">
          <ContextProvider>{children}</ContextProvider>
        </div>
      </body>
    </html>
  );
}
